version: "3.8"

services:
  database:
    container_name: db
    image: mariadb:10.8.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_PASSWORD: password
      MYSQL_USER: app
      UPLOAD_LIMIT: 300M
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - application

  application:
    container_name: app
    build:
      context: .
    volumes:
      - .:/var/www/html:delegated
      - ./docker/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf:delegated
      - ./docker/apache2/symfony.conf:/etc/apache2/sites-available/000-default.conf:delegated
    ports:
      - "80:80"
    networks:
      - application
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:root@database:3306/app?serverVersion=mariadb-10.8.2

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    depends_on:
      - database
    ports:
      - "8181:80"
    environment:
      PMA_HOST: database
    networks:
      - application

networks:
  application:

volumes:
  db-data: